version: '2'
services:
  worker:
    build:
      context: .
      dockerfile: dockerfiles/worker/Dockerfile
    restart: always
    container_name: irk-worker
    volumes:
      - ./data/screenshots:/app/data/screenshots
      - ./data/logs:/app/data/logs
    environment:
      - ENV=production
    depends_on:
      - redis
      - nginx

  bot_telegram:
    build:
      context: .
      dockerfile: dockerfiles/bot_telegram/Dockerfile
    restart: always
    container_name: irk-bot-telegram
    volumes:
      - ./data/logs:/app/data/logs
    depends_on:
      - redis

  bot_slack:
    build:
      context: .
      dockerfile: dockerfiles/bot_slack/Dockerfile
    restart: always
    container_name: irk-bot-slack
    volumes:
      - ./data/logs:/app/data/logs
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - $REDIS_PORT:6379
    container_name: irk-redis
    entrypoint:
      'redis-server --requirepass "$REDIS_PASSWORD"'
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - $NGINX_PORT:80
    container_name: irk-nginx
    volumes:
      - ./data/screenshots:/usr/share/nginx/html/screenshots