version: '2'
services:
  irk-event-worker:
    build:
      context: irk-event-worker
      dockerfile: Dockerfile
    restart: always
    container_name: irk-event-worker
    volumes:
      - ./irk-event-worker/screenshots:/app/data/screenshots
      - ./irk-event-worker/logs:/app/data/logs
    environment:
      - ENV=production
    depends_on:
      - redis
      - nginx

  redis:
    restart: always
    image: redis:latest
    ports:
      - $REDIS_PORT:6379
    container_name: irk-redis
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    entrypoint:
      'redis-server --requirepass "$REDIS_PASSWORD"'
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - $NGINX_PORT:80
    container_name: irk-nginx
    volumes:
      - ./irk-event-worker/screenshots:/var/www/html/screenshots